controllers:
  resource:
    path: ../src/Controller/
    namespace: App\Controller
  type: attribute

review_create:
  path: /review/create
  controller: App\Controller\ReviewController::createReview

index_book:
  path: /
  controller: App\Controller\BookController::home

create_book:
  path: /book/create
  controller: App\Controller\BookController::createBook

view_book:
  path: /book/{id}
  controller: App\Controller\BookController::viewBook


api_login:
  path: /api/v1/login